---
author: ~
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Jifty-Plugin-Chart
no_index:
  directory:
    - inc
    - share
    - t
recommends:
  Chart::Base: 0
  GD: 0
  GD::Graph: 0
  Image::Info: 0
  XML::Simple: 0
requires:
  Jifty: 0
version: undef
